# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mflix_pb2 as mflix__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mflix_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MflixStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarFilme = channel.unary_unary(
                '/mflix.Mflix/CriarFilme',
                request_serializer=mflix__pb2.Pedido.SerializeToString,
                response_deserializer=mflix__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ReadFilme = channel.unary_unary(
                '/mflix.Mflix/ReadFilme',
                request_serializer=mflix__pb2.Pedido.SerializeToString,
                response_deserializer=mflix__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.UpdateFilme = channel.unary_unary(
                '/mflix.Mflix/UpdateFilme',
                request_serializer=mflix__pb2.Pedido.SerializeToString,
                response_deserializer=mflix__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.DeleteFilme = channel.unary_unary(
                '/mflix.Mflix/DeleteFilme',
                request_serializer=mflix__pb2.Pedido.SerializeToString,
                response_deserializer=mflix__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ListaFilmesAtor = channel.unary_unary(
                '/mflix.Mflix/ListaFilmesAtor',
                request_serializer=mflix__pb2.Pedido.SerializeToString,
                response_deserializer=mflix__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ListaFilmesGenero = channel.unary_unary(
                '/mflix.Mflix/ListaFilmesGenero',
                request_serializer=mflix__pb2.Pedido.SerializeToString,
                response_deserializer=mflix__pb2.Confirmacao.FromString,
                _registered_method=True)


class MflixServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriarFilme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFilme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFilme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFilme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListaFilmesAtor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListaFilmesGenero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MflixServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarFilme': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarFilme,
                    request_deserializer=mflix__pb2.Pedido.FromString,
                    response_serializer=mflix__pb2.Confirmacao.SerializeToString,
            ),
            'ReadFilme': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFilme,
                    request_deserializer=mflix__pb2.Pedido.FromString,
                    response_serializer=mflix__pb2.Confirmacao.SerializeToString,
            ),
            'UpdateFilme': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFilme,
                    request_deserializer=mflix__pb2.Pedido.FromString,
                    response_serializer=mflix__pb2.Confirmacao.SerializeToString,
            ),
            'DeleteFilme': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFilme,
                    request_deserializer=mflix__pb2.Pedido.FromString,
                    response_serializer=mflix__pb2.Confirmacao.SerializeToString,
            ),
            'ListaFilmesAtor': grpc.unary_unary_rpc_method_handler(
                    servicer.ListaFilmesAtor,
                    request_deserializer=mflix__pb2.Pedido.FromString,
                    response_serializer=mflix__pb2.Confirmacao.SerializeToString,
            ),
            'ListaFilmesGenero': grpc.unary_unary_rpc_method_handler(
                    servicer.ListaFilmesGenero,
                    request_deserializer=mflix__pb2.Pedido.FromString,
                    response_serializer=mflix__pb2.Confirmacao.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mflix.Mflix', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mflix.Mflix', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mflix(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarFilme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflix.Mflix/CriarFilme',
            mflix__pb2.Pedido.SerializeToString,
            mflix__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFilme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflix.Mflix/ReadFilme',
            mflix__pb2.Pedido.SerializeToString,
            mflix__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFilme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflix.Mflix/UpdateFilme',
            mflix__pb2.Pedido.SerializeToString,
            mflix__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFilme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflix.Mflix/DeleteFilme',
            mflix__pb2.Pedido.SerializeToString,
            mflix__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListaFilmesAtor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflix.Mflix/ListaFilmesAtor',
            mflix__pb2.Pedido.SerializeToString,
            mflix__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListaFilmesGenero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflix.Mflix/ListaFilmesGenero',
            mflix__pb2.Pedido.SerializeToString,
            mflix__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
