# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mflix.proto for package 'mflix'

require 'grpc'
require 'mflix_pb'

module Mflix
  module Mflix
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mflix.Mflix'

      rpc :CriarFilme, ::Mflix::Pedido, ::Mflix::Confirmacao
      rpc :ReadFilme, ::Mflix::Pedido, ::Mflix::Confirmacao
      rpc :UpdateFilme, ::Mflix::Pedido, ::Mflix::Confirmacao
      rpc :DeleteFilme, ::Mflix::Pedido, ::Mflix::Confirmacao
      rpc :ListaFilmesAtor, ::Mflix::Pedido, ::Mflix::Confirmacao
      rpc :ListaFilmesGenero, ::Mflix::Pedido, ::Mflix::Confirmacao
    end

    Stub = Service.rpc_stub_class
  end
end
